version: "2.1"
services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${HOME_DIR}/docker-config/bazarr/config:/config
      - ${HOME_DIR}/movies:/movies
      - ${HOME_DIR}/series:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
