version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ${HOME_DIR}/home-assistant/config:/config
    environment:
      - TZ=Europe/Madrid
    restart: unless-stopped
    network_mode: host
