version: "2.1"
services:
  influxdb:
    image: ghcr.io/terjesannum/influxdb-arm32:1.8.10-1
    container_name: influxdb_container
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - ${HOME_DIR}/docker-config/influxdb/volume:/var/lib/influxdb
    environment:
     INFLUXDB_DB: ${INFLUXDB_DB}
     INFLUXDB_HTTP_AUTH_ENABLED: 'true'
     INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
     INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
     INFLUXDB_USER: ${INFLUXDB_USER}
     INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
     INFLUXDB_MONITOR_STORE_ENABLED: 'false'
