version: "2.1"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${HOME_DIR}/docker-config/sonarr/config:/config
      - ${HOME_DIR}/series:/tv
      - ${HOME_DIR}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
